# Numpy Tricks

## np.sort
np.sort() returns a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
import numpy as np
a= np.random.randint(1,100,15)
a

array([80, 61, 20, 20,  6, 77, 81, 31,  1, 73, 25, 49, 28, 53, 24])

In [4]:
b= np.random.randint(1,100,24).reshape(6,4)
b

array([[ 1, 16, 17,  9],
       [17, 95, 19, 13],
       [ 9, 54, 73, 50],
       [16, 60, 90, 64],
       [86, 24, 91, 79],
       [20, 54, 41, 51]])

In [5]:
np.sort(a)

array([ 1,  6, 20, 20, 24, 25, 28, 31, 49, 53, 61, 73, 77, 80, 81])

In [6]:
np.sort(a)[::-1]

array([81, 80, 77, 73, 61, 53, 49, 31, 28, 25, 24, 20, 20,  6,  1])

In [7]:
# axis=0 means columns and axis=1 means rows
np.sort(b, axis=0)

array([[ 1, 16, 17,  9],
       [ 9, 24, 19, 13],
       [16, 54, 41, 50],
       [17, 54, 73, 51],
       [20, 60, 90, 64],
       [86, 95, 91, 79]])

## np.append
The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [8]:
np.append(a,200)

array([ 80,  61,  20,  20,   6,  77,  81,  31,   1,  73,  25,  49,  28,
        53,  24, 200])

In [10]:
b

array([[ 1, 16, 17,  9],
       [17, 95, 19, 13],
       [ 9, 54, 73, 50],
       [16, 60, 90, 64],
       [86, 24, 91, 79],
       [20, 54, 41, 51]])

In [17]:
(b.shape[0],1)

(6, 1)

In [11]:
np.append(b, np.random.random((b.shape[0],1)), axis=1)

array([[ 1.        , 16.        , 17.        ,  9.        ,  0.45846975],
       [17.        , 95.        , 19.        , 13.        ,  0.47038503],
       [ 9.        , 54.        , 73.        , 50.        ,  0.79441355],
       [16.        , 60.        , 90.        , 64.        ,  0.54942327],
       [86.        , 24.        , 91.        , 79.        ,  0.53057452],
       [20.        , 54.        , 41.        , 51.        ,  0.90580587]])

## np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [19]:
c= np.arange(6).reshape(2,3)
d= np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [20]:
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [21]:
np.concatenate((c,d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [22]:
e= np.array([1,1,2,2,3,3,3,4,4,4,5,5,6,7])

In [23]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

## np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [27]:
a

array([80, 61, 20, 20,  6, 77, 81, 31,  1, 73, 25, 49, 28, 53, 24])

In [24]:
a.shape

(15,)

In [26]:
np.expand_dims(a, axis=0)

array([[80, 61, 20, 20,  6, 77, 81, 31,  1, 73, 25, 49, 28, 53, 24]])

In [25]:
np.expand_dims(a, axis=0).shape

(1, 15)

In [28]:
np.expand_dims(a, axis=1)

array([[80],
       [61],
       [20],
       [20],
       [ 6],
       [77],
       [81],
       [31],
       [ 1],
       [73],
       [25],
       [49],
       [28],
       [53],
       [24]])

In [29]:
np.expand_dims(a, axis=1).shape

(15, 1)

## np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [30]:
a

array([80, 61, 20, 20,  6, 77, 81, 31,  1, 73, 25, 49, 28, 53, 24])

In [32]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  5,  6,  9, 13], dtype=int64),)

In [33]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0, 20, 20,  6,  0,  0, 31,  1,  0, 25, 49, 28,  0, 24])

In [34]:
np.where(a%2==0,0,a)

array([ 0, 61,  0,  0,  0, 77, 81, 31,  1, 73, 25, 49,  0, 53,  0])

## np.argmax & np.argmin
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

The numpy.argmin() function returns indices of the min element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [35]:
a

array([80, 61, 20, 20,  6, 77, 81, 31,  1, 73, 25, 49, 28, 53, 24])

In [36]:
np.argmax(a)

6

In [37]:
b

array([[ 1, 16, 17,  9],
       [17, 95, 19, 13],
       [ 9, 54, 73, 50],
       [16, 60, 90, 64],
       [86, 24, 91, 79],
       [20, 54, 41, 51]])

In [39]:
np.argmax(b, axis=0)

array([4, 1, 4, 4], dtype=int64)

In [40]:
np.argmax(b, axis=1)

array([2, 1, 2, 2, 2, 1], dtype=int64)

In [41]:
np.argmin(a)

8

In [43]:
np.argmin(b, axis=0)

array([0, 0, 0, 0], dtype=int64)

In [44]:
np.argmin(b, axis=1)

array([0, 3, 0, 0, 1, 0], dtype=int64)

## np.cumsum & np.cumprod
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.
numpy.cumprod() function is used when we want to compute the cumulative product of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [45]:
a

array([80, 61, 20, 20,  6, 77, 81, 31,  1, 73, 25, 49, 28, 53, 24])

In [46]:
np.cumsum(a)

array([ 80, 141, 161, 181, 187, 264, 345, 376, 377, 450, 475, 524, 552,
       605, 629], dtype=int32)

In [47]:
b

array([[ 1, 16, 17,  9],
       [17, 95, 19, 13],
       [ 9, 54, 73, 50],
       [16, 60, 90, 64],
       [86, 24, 91, 79],
       [20, 54, 41, 51]])

In [49]:
np.cumsum(b, axis=0)

array([[  1,  16,  17,   9],
       [ 18, 111,  36,  22],
       [ 27, 165, 109,  72],
       [ 43, 225, 199, 136],
       [129, 249, 290, 215],
       [149, 303, 331, 266]], dtype=int32)

In [48]:
np.cumsum(b, axis=1)

array([[  1,  17,  34,  43],
       [ 17, 112, 131, 144],
       [  9,  63, 136, 186],
       [ 16,  76, 166, 230],
       [ 86, 110, 201, 280],
       [ 20,  74, 115, 166]], dtype=int32)

In [50]:
# cumulative sum by rows
np.cumsum(b)

array([   1,   17,   34,   43,   60,  155,  174,  187,  196,  250,  323,
        373,  389,  449,  539,  603,  689,  713,  804,  883,  903,  957,
        998, 1049], dtype=int32)

In [52]:
a

array([80, 61, 20, 20,  6, 77, 81, 31,  1, 73, 25, 49, 28, 53, 24])

In [51]:
np.cumprod(a)

array([         80,        4880,       97600,     1952000,    11712000,
         901824000,    33299968,  1032299008,  1032299008, -1951583744,
       -1544953344,  1606697472,  2037856256,   632199168, -2007089152],
      dtype=int32)

## np.percentile
numpy.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [53]:
a

array([80, 61, 20, 20,  6, 77, 81, 31,  1, 73, 25, 49, 28, 53, 24])

In [54]:
np.percentile(a, 50)

31.0

In [55]:
np.median(a)

31.0

## np.histogram
Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [56]:
a

array([80, 61, 20, 20,  6, 77, 81, 31,  1, 73, 25, 49, 28, 53, 24])

In [57]:
np.histogram(a, bins= [10,20,30,40,50,60,70,80,90])

(array([0, 5, 1, 1, 1, 1, 2, 2], dtype=int64),
 array([10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [58]:
np.histogram(a,bins=[0,50,100])

(array([9, 6], dtype=int64), array([  0,  50, 100]))

## np.corrcoef
Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [59]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [60]:
a

array([80, 61, 20, 20,  6, 77, 81, 31,  1, 73, 25, 49, 28, 53, 24])

In [61]:
items = [10,20,30,40,50,60,70,80,90,100]

In [63]:
a[np.isin(a, items)]

array([80, 20, 20])

## np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [64]:
a

array([80, 61, 20, 20,  6, 77, 81, 31,  1, 73, 25, 49, 28, 53, 24])

In [65]:
np.flip(a)

array([24, 53, 28, 49, 25, 73,  1, 31, 81, 77,  6, 20, 20, 61, 80])

In [66]:
b

array([[ 1, 16, 17,  9],
       [17, 95, 19, 13],
       [ 9, 54, 73, 50],
       [16, 60, 90, 64],
       [86, 24, 91, 79],
       [20, 54, 41, 51]])

In [68]:
np.flip(b, axis=0)

array([[20, 54, 41, 51],
       [86, 24, 91, 79],
       [16, 60, 90, 64],
       [ 9, 54, 73, 50],
       [17, 95, 19, 13],
       [ 1, 16, 17,  9]])

In [69]:
np.flip(b, axis=1)

array([[ 9, 17, 16,  1],
       [13, 19, 95, 17],
       [50, 73, 54,  9],
       [64, 90, 60, 16],
       [79, 91, 24, 86],
       [51, 41, 54, 20]])

## np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [70]:
a

array([80, 61, 20, 20,  6, 77, 81, 31,  1, 73, 25, 49, 28, 53, 24])

In [71]:
np.put(a, [0, 1], [110, 530])

In [72]:
a

array([110, 530,  20,  20,   6,  77,  81,  31,   1,  73,  25,  49,  28,
        53,  24])

## np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [73]:
a

array([110, 530,  20,  20,   6,  77,  81,  31,   1,  73,  25,  49,  28,
        53,  24])

In [74]:
np.delete(a, [0,1])

array([20, 20,  6, 77, 81, 31,  1, 73, 25, 49, 28, 53, 24])

## Set functions

* np.union1d
* np.intersect1d
* np.setdiff1d
* np.setxor1d
* np.in1d

In [77]:
# np.union1d gives the union of the two array where it takes only unique values of both the array

m= np.array([1,2,3,4,5,6,7])
n= np.array([3,4,5,6,7,8,9,10])

np.union1d(m,n)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
# np.intersect1d gives the intersection of the two array which means the common elements of both the array

np.intersect1d(m,n)

array([3, 4, 5, 6, 7])

In [79]:
# np.setdiff1d gives the uncommon element of the array
# np.setdiff1d(m,n) gives the uncommon or unique elements of m

np.setdiff1d(m,n)

array([1, 2])

In [81]:
# np.setdiff1d(n,m) gives the uncommon or unique elements of n 

np.setdiff1d(n,m)

array([ 8,  9, 10])

In [80]:
# np.setxor1d gives the unique element of both the arrays

np.setxor1d(m,n)

array([ 1,  2,  8,  9, 10])

In [92]:
# numpy.in1d(ar1, ar2) Tests whether each element of a 1-D array is also present in a second array.
# np.in1d(m,1) tests whether 1 is present is m or not.

m[np.in1d(m,4)]

array([4])

In [94]:
# 0 is not present in m
m[np.in1d(m,0)]

array([], dtype=int32)

In [93]:
n[np.in1d(n,5)]

array([5])

In [95]:
# 14 is not present in n
n[np.in1d(n,14)]

array([], dtype=int32)

## np.clip
numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [96]:
a

array([110, 530,  20,  20,   6,  77,  81,  31,   1,  73,  25,  49,  28,
        53,  24])

In [97]:
# number > 75 will be mapped to 75 and the number < 25 will be mapped to 25, rest numbers between 27 to 75 will remain 
# as it is without any change
np.clip(a, a_min=25, a_max= 75)

array([75, 75, 25, 25, 25, 75, 75, 31, 25, 73, 25, 49, 28, 53, 25])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:
# 25. np.allclose and equals