# Numpy

## What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

## Numpy Arrays Vs Python Sequences

* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating Numpy Arrays

In [1]:
# numpy array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
# with reshape
np.arange(1, 11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [6]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [8]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# np.ones and np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# np.random
np.random.random((3,4))

array([[0.72801668, 0.18244308, 0.99260545, 0.3652297 ],
       [0.11823817, 0.83193959, 0.48989397, 0.25012719],
       [0.57598004, 0.5475538 , 0.28897647, 0.845085  ]])

In [11]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [12]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [13]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
# ndim
a3.ndim

3

In [15]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [17]:
# itemsize
a3.itemsize

4

In [18]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


## Changing Datatype

In [20]:
a3.dtype

dtype('int32')

In [21]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## Array Operations

In [22]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [24]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [25]:
# vector operations
# arithmetic
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]], dtype=int32)

## Array Functions

In [28]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 5., 25., 75.],
       [59., 77., 94.],
       [48., 53., 56.]])

In [29]:
# max/min/sum/prod
np.max(a1)

94.0

In [30]:
# max/min/sum/prod
np.prod(a1)

570357295200000.0

In [31]:
# max/min/sum/prod
np.min(a1)

5.0

In [32]:
# max/min/sum/prod
np.sum(a1)

492.0

In [34]:
# To get the min of every row
# 0-> column and 1-> row
np.min(a1, axis= 1)

array([ 5., 59., 48.])

In [35]:
# To get the product of every row
np.prod(a1, axis= 1)

array([  9375., 427042., 142464.])

In [36]:
# mean/median/std/var
np.mean(a1,axis=1)

array([35.        , 76.66666667, 52.33333333])

In [37]:
# mean/median/std/var
np.median(a1,axis=1)

array([25., 77., 53.])

In [38]:
# mean/median/std/var
np.std(a1,axis=1)

array([29.43920289, 14.29063407,  3.29983165])

In [39]:
# mean/median/std/var
np.var(a1,axis=1)

array([866.66666667, 204.22222222,  10.88888889])

In [40]:
# trigonomoetric functions
np.sin(a1)

array([[-0.95892427, -0.13235175, -0.38778164],
       [ 0.63673801,  0.99952016, -0.24525199],
       [-0.76825466,  0.39592515, -0.521551  ]])

In [41]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [42]:
# log and exponents
np.log(a1)

array([[1.60943791, 3.21887582, 4.31748811],
       [4.07753744, 4.34380542, 4.54329478],
       [3.87120101, 3.97029191, 4.02535169]])

In [43]:
# log and exponents
np.exp(a1)

array([[1.48413159e+02, 7.20048993e+10, 3.73324200e+32],
       [4.20121040e+25, 2.75851345e+33, 6.66317622e+40],
       [7.01673591e+20, 1.04137594e+23, 2.09165950e+24]])

In [44]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[19., 74., 95.],
       [84., 43., 35.]])

In [45]:
# round/floor/ceil

np.floor(np.random.random((2,3))*100)

array([[ 1., 14., 66.],
       [43., 74., 98.]])

In [46]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[60., 93., 71.],
       [34., 49., 68.]])

## Indexing and Slicing

In [47]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a1[-1]

9

In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
# Fetching 6 from a 2d matrix
a2[1,2]

6

In [53]:
# Fetching 11 from a 2d matrix
a2[2,3]

11

In [54]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [56]:
# Fetching the item from a 3d matrix
a3[1,0,1]

5

In [58]:
a3[0,0,0]

0

In [59]:
a3[1,1,0]

6

In [61]:
## Slicing -> Fetching multiple items from an array
print(a1)
a1[2:5:2]

[0 1 2 3 4 5 6 7 8 9]


array([2, 4])

In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a2[0,:]

array([0, 1, 2, 3])

In [64]:
a2[:,2]

array([ 2,  6, 10])

In [65]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [66]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [69]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [72]:
a2[1, 0::3]

array([4, 7])

In [76]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [77]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [78]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [79]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [80]:
a3[0,1]

array([3, 4, 5])

In [82]:
a3[1,:,1]

array([10, 13, 16])

In [84]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [95]:
a3[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [97]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [99]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [101]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [102]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [103]:
## Converting 3d array into 1 dimensional array and printing it
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [ ]:
# reshape is already discussed in the above code 

In [104]:
# Transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [105]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [106]:
# ravel converts multi dimensional array to a single dimensional array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [107]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [108]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [112]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [114]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [113]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [115]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
# horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [119]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [122]:
# vertical splitting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]